spring:
  datasource:
    url: jdbc:h2:./devdb
    username: sa
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update